# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_closest_center_interface <- function(data_mat, centers_mat) {
    .Call(`_anRpackage_find_closest_center_interface`, data_mat, centers_mat)
}

